-- ============================================
-- ASIS Oracle 초기화 스크립트
-- 00. 사용자 생성 및 권한 부여
-- ============================================

-- PDB로 전환 (CDB에서 실행되는 경우 대비)
ALTER SESSION SET CONTAINER = XEPDB1;

-- ASIS_USER가 없으면 생성 (이미 있으면 무시)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM DBA_USERS WHERE username = 'ASIS_USER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ASIS_USER IDENTIFIED BY asis123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
END;
/

-- 권한 부여
GRANT CONNECT, RESOURCE TO ASIS_USER;
GRANT CREATE SESSION TO ASIS_USER;
GRANT CREATE TABLE TO ASIS_USER;
GRANT CREATE PROCEDURE TO ASIS_USER;
GRANT CREATE SEQUENCE TO ASIS_USER;
GRANT CREATE VIEW TO ASIS_USER;
GRANT CREATE JOB TO ASIS_USER;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ASIS_USER;

-- 확인
SELECT username, account_status FROM DBA_USERS WHERE username = 'ASIS_USER';
