-- ============================================
-- ASIS Oracle 초기화 스크립트
-- 05. 샘플 데이터 입력
-- ============================================

-- 레거시 코드 마스터
INSERT INTO LEGACY_CODE (CODE_ID, CODE_NAME, USE_YN) VALUES ('CAT01', '문학', 'Y');
INSERT INTO LEGACY_CODE (CODE_ID, CODE_NAME, USE_YN) VALUES ('CAT02', '과학', 'Y');
INSERT INTO LEGACY_CODE (CODE_ID, CODE_NAME, USE_YN) VALUES ('CAT03', '역사', 'Y');
INSERT INTO LEGACY_CODE (CODE_ID, CODE_NAME, USE_YN) VALUES ('STS01', '활성', 'Y');
INSERT INTO LEGACY_CODE (CODE_ID, CODE_NAME, USE_YN) VALUES ('STS02', '비활성', 'Y');

-- 도서 정보
INSERT INTO BOOK_INFO (BOOK_ID, BOOK_TITLE, AUTHOR, CATEGORY, STATUS)
VALUES (1, '홍길동전', '허균', '01', 'Y');
INSERT INTO BOOK_INFO (BOOK_ID, BOOK_TITLE, AUTHOR, CATEGORY, STATUS)
VALUES (2, '상대성이론', '아인슈타인', '02', 'Y');
INSERT INTO BOOK_INFO (BOOK_ID, BOOK_TITLE, AUTHOR, CATEGORY, STATUS)
VALUES (3, '조선왕조실록', '미상', '03', 'Y');

-- 회원 정보
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_NAME, EMAIL, MEMBER_TYPE, STATUS)
VALUES (1, '홍길동', 'hong@test.com', 'A', 'Y');
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_NAME, EMAIL, MEMBER_TYPE, STATUS)
VALUES (2, '김철수', 'kim@test.com', 'B', 'Y');
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_NAME, EMAIL, MEMBER_TYPE, STATUS)
VALUES (3, '이영희', 'lee@test.com', 'C', 'Y');

COMMIT;

-- 데이터 확인
SELECT 'LEGACY_CODE' AS TABLE_NAME, COUNT(*) AS CNT FROM LEGACY_CODE
UNION ALL
SELECT 'BOOK_INFO', COUNT(*) FROM BOOK_INFO
UNION ALL
SELECT 'MEMBER_INFO', COUNT(*) FROM MEMBER_INFO
UNION ALL
SELECT 'NEW_SERVICE_RECV', COUNT(*) FROM NEW_SERVICE_RECV;
