-- ============================================
-- TOBE Oracle 초기화 스크립트
-- 01. 원본 테이블 생성 (신 스키마 - 표준화)
-- ============================================

-- PDB로 전환
ALTER SESSION SET CONTAINER = XEPDB1;

-- TOBE_USER 스키마로 전환
ALTER SESSION SET CURRENT_SCHEMA = TOBE_USER;

-- 레거시 코드 수신용 (ASIS→TOBE 단방향)
CREATE TABLE TB_LEGACY_CODE (
    CODE_ID         VARCHAR2(10) PRIMARY KEY,
    CODE_NAME       VARCHAR2(200),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(50) DEFAULT 'SYSTEM'
);

-- 도서 정보 (양방향)
CREATE TABLE TB_BOOK (
    BOOK_ID         NUMBER PRIMARY KEY,
    TITLE           VARCHAR2(500) NOT NULL,
    AUTHOR_NAME     VARCHAR2(200),
    CATEGORY_CD     VARCHAR2(10),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CREATED_BY      VARCHAR2(50) DEFAULT 'SYSTEM',
    UPDATED_BY      VARCHAR2(50)
);

-- 회원 정보 (양방향)
CREATE TABLE TB_MEMBER (
    MEMBER_ID       NUMBER PRIMARY KEY,
    MEMBER_NAME     VARCHAR2(100) NOT NULL,
    EMAIL_ADDR      VARCHAR2(200),
    MEMBER_TYPE_CD  VARCHAR2(10),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
);

-- 신규 서비스 (TOBE→ASIS 단방향)
CREATE TABLE TB_NEW_SERVICE (
    SERVICE_ID      NUMBER PRIMARY KEY,
    SERVICE_NAME    VARCHAR2(200) NOT NULL,
    SERVICE_TYPE_CD VARCHAR2(20),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 테이블 생성 확인
SELECT table_name FROM user_tables ORDER BY table_name;
