-- ============================================
-- TOBE Oracle 초기화 스크립트
-- 02. CDC 관련 테이블 생성
-- ============================================

-- PDB로 전환
ALTER SESSION SET CONTAINER = XEPDB1;

-- TOBE_USER 스키마로 전환
ALTER SESSION SET CURRENT_SCHEMA = TOBE_USER;

-- CDC_TOBE_TABLES: ASIS에서 받은 데이터 저장
CREATE TABLE CDC_TOBE_LEGACY_CODE (
    CDC_SEQ         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATION       VARCHAR2(10) NOT NULL,
    CODE_ID         VARCHAR2(10),
    CODE_NAME       VARCHAR2(100),
    USE_YN          CHAR(1),
    REG_DATE        DATE,                   -- LEGACY_CODE에서 전송되는 컬럼
    SOURCE_TIMESTAMP TIMESTAMP,
    RECEIVED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000),
    CHANGE_HASH     VARCHAR2(64)
);

CREATE TABLE CDC_TOBE_BOOK (
    CDC_SEQ         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATION       VARCHAR2(10) NOT NULL,
    BOOK_ID         NUMBER,
    BOOK_TITLE      VARCHAR2(200),
    AUTHOR          VARCHAR2(100),
    CATEGORY        VARCHAR2(2),
    STATUS          CHAR(1),
    REG_DATE        DATE,
    MOD_DATE        DATE,
    SOURCE_TIMESTAMP TIMESTAMP,
    RECEIVED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000),
    CHANGE_HASH     VARCHAR2(64)
);

CREATE TABLE CDC_TOBE_MEMBER (
    CDC_SEQ         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATION       VARCHAR2(10) NOT NULL,
    MEMBER_ID       NUMBER,
    MEMBER_NAME     VARCHAR2(50),
    EMAIL           VARCHAR2(100),
    MEMBER_TYPE     CHAR(1),
    STATUS          CHAR(1),
    REG_DATE        DATE,
    SOURCE_TIMESTAMP TIMESTAMP,
    RECEIVED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000),
    CHANGE_HASH     VARCHAR2(64)
);

-- STAGING 테이블: 스키마 변환 후 대기
CREATE TABLE STAGING_TOBE_LEGACY_CODE (
    STAGING_SEQ     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CDC_SEQ         NUMBER,
    OPERATION       VARCHAR2(10) NOT NULL,
    CODE_ID         VARCHAR2(10),
    CODE_NAME       VARCHAR2(200),
    IS_ACTIVE       NUMBER(1),
    CREATED_BY      VARCHAR2(50),
    STAGED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000)
);

CREATE TABLE STAGING_TOBE_BOOK (
    STAGING_SEQ     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CDC_SEQ         NUMBER,
    OPERATION       VARCHAR2(10) NOT NULL,
    BOOK_ID         NUMBER,
    TITLE           VARCHAR2(500),
    AUTHOR_NAME     VARCHAR2(200),
    CATEGORY_CD     VARCHAR2(10),
    IS_ACTIVE       NUMBER(1),
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    STAGED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000)
);

CREATE TABLE STAGING_TOBE_MEMBER (
    STAGING_SEQ     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CDC_SEQ         NUMBER,
    OPERATION       VARCHAR2(10) NOT NULL,
    MEMBER_ID       NUMBER,
    MEMBER_NAME     VARCHAR2(100),
    EMAIL_ADDR      VARCHAR2(200),
    MEMBER_TYPE_CD  VARCHAR2(10),
    IS_ACTIVE       NUMBER(1),
    CREATED_AT      TIMESTAMP,
    STAGED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_YN    CHAR(1) DEFAULT 'N',
    PROCESSED_AT    TIMESTAMP,
    ERROR_MSG       VARCHAR2(1000)
);

-- 동기화 로그 테이블
CREATE TABLE CDC_SYNC_LOG (
    LOG_SEQ         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOG_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    DIRECTION       VARCHAR2(20),  -- ASIS_TO_TOBE
    TABLE_NAME      VARCHAR2(100),
    OPERATION       VARCHAR2(10),
    PK_VALUE        VARCHAR2(100),
    STATUS          VARCHAR2(20),
    ERROR_CODE      VARCHAR2(20),
    ERROR_MSG       VARCHAR2(1000),
    CHANGE_HASH     VARCHAR2(64)
);

-- 처리된 해시 저장 (무한루프 방지)
CREATE TABLE CDC_PROCESSED_HASH (
    HASH_VALUE      VARCHAR2(64) PRIMARY KEY,
    TABLE_NAME      VARCHAR2(100),
    PK_VALUE        VARCHAR2(100),
    PROCESSED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IDX_CDC_TOBE_LEGACY_PROC ON CDC_TOBE_LEGACY_CODE(PROCESSED_YN);
CREATE INDEX IDX_CDC_TOBE_BOOK_PROC ON CDC_TOBE_BOOK(PROCESSED_YN);
CREATE INDEX IDX_CDC_TOBE_MEMBER_PROC ON CDC_TOBE_MEMBER(PROCESSED_YN);
CREATE INDEX IDX_STAGING_TOBE_LEGACY_PROC ON STAGING_TOBE_LEGACY_CODE(PROCESSED_YN);
CREATE INDEX IDX_STAGING_TOBE_BOOK_PROC ON STAGING_TOBE_BOOK(PROCESSED_YN);
CREATE INDEX IDX_STAGING_TOBE_MEMBER_PROC ON STAGING_TOBE_MEMBER(PROCESSED_YN);
CREATE INDEX IDX_CDC_HASH_TABLE ON CDC_PROCESSED_HASH(TABLE_NAME, PK_VALUE);
