-- ============================================
-- TOBE Oracle 초기화 스크립트
-- 05. 샘플 데이터 입력
-- ============================================

-- 도서 정보 (ASIS와 동일한 데이터를 TOBE 스키마로)
INSERT INTO TB_BOOK (BOOK_ID, TITLE, AUTHOR_NAME, CATEGORY_CD, IS_ACTIVE)
VALUES (1, '홍길동전', '허균', 'LIT', 1);
INSERT INTO TB_BOOK (BOOK_ID, TITLE, AUTHOR_NAME, CATEGORY_CD, IS_ACTIVE)
VALUES (2, '상대성이론', '아인슈타인', 'SCI', 1);
INSERT INTO TB_BOOK (BOOK_ID, TITLE, AUTHOR_NAME, CATEGORY_CD, IS_ACTIVE)
VALUES (3, '조선왕조실록', '미상', 'HIS', 1);

-- 회원 정보
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL_ADDR, MEMBER_TYPE_CD, IS_ACTIVE)
VALUES (1, '홍길동', 'hong@test.com', 'ADMIN', 1);
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL_ADDR, MEMBER_TYPE_CD, IS_ACTIVE)
VALUES (2, '김철수', 'kim@test.com', 'USER', 1);
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL_ADDR, MEMBER_TYPE_CD, IS_ACTIVE)
VALUES (3, '이영희', 'lee@test.com', 'GUEST', 1);

-- 신규 서비스 (TOBE에서만 관리)
INSERT INTO TB_NEW_SERVICE (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_CD, IS_ACTIVE)
VALUES (1, 'AI 추천 서비스', 'AI', 1);
INSERT INTO TB_NEW_SERVICE (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_CD, IS_ACTIVE)
VALUES (2, '모바일 앱 서비스', 'MOBILE', 1);

COMMIT;

-- 데이터 확인
SELECT 'TB_LEGACY_CODE' AS TABLE_NAME, COUNT(*) AS CNT FROM TB_LEGACY_CODE
UNION ALL
SELECT 'TB_BOOK', COUNT(*) FROM TB_BOOK
UNION ALL
SELECT 'TB_MEMBER', COUNT(*) FROM TB_MEMBER
UNION ALL
SELECT 'TB_NEW_SERVICE', COUNT(*) FROM TB_NEW_SERVICE;
